title: JGworkshop
name: JGworkshop
email: jgworkshop3360@gmail.com
description: JGworkshop에서 만든 블로그입니다.

baseurl:
url: ""

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

project_one: "First Project"
project_one_description: Describe your project!
project_one_url: https://github.com/jameshamann/jekyll-material-theme
project_one_icon: location_on

project_two: Second Project
project_two_description: Describe your project!
project_two_url: https://github.com/jameshamann/jekyll-material-theme
project_two_icon: photo_camera


project_three: Third Project
project_three_description: Describe your project!
project_three_url: https://github.com/jameshamann/jekyll-material-theme
project_three_icon: hotel


project_four: Fourth Project
project_four_description: Describe your project!
project_four_url: https://github.com/jameshamann/jekyll-material-theme
project_four_icon: restaurant

portfolio_heading: Portfolio
portfolio_type: cards

syntax_highlighting: true
# Skill icons from https://konpa.github.io/devicon/

skills:
  - name: android
  - name: apple
  - name: c
  - name: cplusplus
  - name: csharp
  - name: css3
  - name: html5
  - name: java
  - name: oracle
  - name: javascript
  - name: nodejs
  - name: php
  - name: phpstorm
  - name: python
  - name: pycharm
  - name: ruby
  - name: debian
  - name: linux
  - name: ubuntu
  - name: dot-net
  - name: git
  - name: github
  - name: illustrator
  - name: photoshop
  - name: safari
  - name: chrome
  - name: ie10
  - name: firefox
  - name: google
  - name: sourcetree
  - name: ssh
  - name: twitter
  - name: facebook
  - name: visualstudio
  - name: windows10

icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Github

github: https://github.com/jgworkshop3360
medium: ttps://github.com/jgworkshop3360

baseurl: # if your site is located at /blog or /home, enter it here, otherwise leave it empty
url: http://localhost:4000/ #the url of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookies_banner: show # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: Thanks!

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
